spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.mode=${DB_MODE}
spring.datasource.channel_binding=${DB_CHANNEL_BINDING}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=1H8KMmCwLx4yg6GYSSOY3JXt3eZhU3liZS2SdI3wvlw=
jwt.token.lifespan=3600000