spring.application.name=1-flashcard

#jdbc:postgresql://ep-super-river-ab15ua67-pooler.eu-west-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_4HYlRftyodM1&sslmode=require&channelBinding=require
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.mode=${DB_MODE}
spring.datasource.channel_binding=${DB_CHANNEL_BINDING}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect