spring.application.name=1-flashcard


spring.datasource.url=jdbc:postgresql://ep-super-river-ab15ua67-pooler.eu-west-2.aws.neon.tech/neondb?user=neondb_owner&password=npg_4HYlRftyodM1&sslmode=require&channelBinding=require
#spring.datasource.username=
#spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect